name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: nodejs-microservices

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314113909414:role/GitHubActions-ECR-NodeMicroservices
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images
        run: docker compose build

      - name: Tag Gateway image
        run: |
          docker tag gateway:latest \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:gateway-latest

      - name: Tag Worker image
        run: |
          docker tag worker:latest \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:worker-latest

      - name: Push Gateway image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:gateway-latest

      - name: Push Worker image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:worker-latest